# Generated by Django 3.2 on 2022-02-15 20:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('landscaping', models.BooleanField()),
                ('maintenance', models.BooleanField()),
                ('tree', models.BooleanField()),
                ('design', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('landscaping', models.BooleanField()),
                ('maintenance', models.BooleanField()),
                ('tree', models.BooleanField()),
                ('design', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
