# Generated by Django 3.2 on 2022-04-16 07:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20220413_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='needs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('garden-maintenance', 'Garden-Maintenance'), ('garden-design', 'Garden-Design'), ('landscaping', 'Landscaping'), ('tree-surgery', 'Tree-Surgery')], max_length=57),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=17),
        ),
    ]
