# Generated by Django 3.2 on 2022-02-18 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
