# Generated by Django 3.2 on 2022-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_business_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
